version: 0.2

phases:
  pre_build:
    commands:
      - echo prebuildphase

  build:
    commands:
      - cd function
      - ls -R
      - echo Installing source Python dependencies...
      - pip3 install Pillow==8.4.0
      - echo Zipping the Lambda function code...
      - zip -r lambda_function_payload.zip .

  post_build:
    commands:
      - echo Build completed
      - echo Deploying Lambda function...
      - aws lambda update-function-code --function-name eagler-image_processor --zip-file fileb://lambda_function_payload.zip